Upgrade v4.67.0 (#2521)
* Upgrade upstream to v4.67.0

- Add patch to elbv2 target_group to fix #2517

* Upgrade upstream patcher tool

Contains new global-replace which means we can call the commands within the old "apply" command ourselves with more customisation.

* Replace repetitive rules with global rules

* Update modules

* Fix up more replacements

- Remove TODOs.
- Fix tags all - literal string changed to a constant.
- Add auto-naming global rule.

* Add new module for autonaming

* Generate schema

* Generate SDKs

Skipping dotnet for now due to:

error: emitting file Quicksight/Outputs/TemplateDefinitionSheetVisualGeospatialMapVisualChartConfigurationFieldWellsGeospatialMapAggregatedFieldWellsValueNumericalMeasureFieldFormatConfigurationNumericFormatConfigurationPercentageDisplayFormatConfigurationSeparatorConfigurationThousandsSeparator.cs: creating file: open /Users/dan/Dev/pulumi-aws/sdk/dotnet/Quicksight/Outputs/TemplateDefinitionSheetVisualGeospatialMapVisualChartConfigurationFieldWellsGeospatialMapAggregatedFieldWellsValueNumericalMeasureFieldFormatConfigurationNumericFormatConfigurationPercentageDisplayFormatConfigurationSeparatorConfigurationThousandsSeparator.cs: file name too long

* Temp: Remove problematic quicksight template definition property

* Re-generate SDKs

* Upgrade java to fix zip file count limit

* Re-run tfgen for missing replacements

* Regenerate SDKs once again

* Test pinning Pulumi CLI version

* Test removing main from nodejs examples

- This seems to be a left-over from how these perhaps used to be run.
- Revert downgrade of Pulumi CLI

---------

Co-authored-by: Thomas Kappler <tkappler@pulumi.com>