Improve error messages around AWS config (#3310)
Should fully address https://github.com/pulumi/pulumi-aws/issues/2285
after https://github.com/pulumi/pulumi-terraform-bridge/pull/1640

This makes the error messages when the user has no credentials or no
region configured better and more actionable:

Before, no credentials configured:

```
error: pulumi:providers:aws resource 'default_6_18_2' has a problem: could not validate provider configuration: unable to validate AWS credentials.
    Details: No valid credential sources found. Please see https://www.pulumi.com/registry/packages/aws/installation-configuration/
    for more information about providing credentials.

    Error: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, request canceled, context deadline exceeded

    Make sure you have set your AWS region, e.g. `pulumi config set aws:region us-west-2`.
```

The line about the region is irrelevant here.

After, no credentials configured:
```
Diagnostics:
  pulumi:providers:aws (default_6_18_2):
    error: pulumi:providers:aws resource 'default_6_18_2' has a problem: could not validate provider configuration: unable to validate AWS credentials.
    Details: No valid credential sources found. Please see https://www.pulumi.com/registry/packages/aws/installation-configuration/
    for more information about providing credentials.

    Error: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, request canceled, context deadline exceeded
```


Before, no region configured:
```
Diagnostics:
  pulumi:providers:aws (default_6_18_2):
    error: pulumi:providers:aws resource 'default_6_18_2' has a problem: could not validate provider configuration: unable to validate AWS credentials.
    Details: validating provider credentials: retrieving caller identity from STS: operation error STS: GetCallerIdentity, https response error StatusCode: 0, RequestID: , request send failed, Post "https://sts..amazonaws.com/": dial tcp: lookup sts..amazonaws.com: no such host
    Make sure you have set your AWS region, e.g. `pulumi config set aws:region us-west-2`.
```

Here, it is not at all clear that it is the region at fault, since the
note about setting the region shows up every time.

After, no region configured:
```
Diagnostics:
  pulumi:providers:aws (default_6_18_2):
    error: pulumi:providers:aws resource 'default_6_18_2' has a problem: could not validate provider configuration: missing region information
    Make sure you have set your AWS region, e.g. `pulumi config set aws:region us-west-2`.
    Details: validating provider credentials: retrieving caller identity from STS: operation error STS: GetCallerIdentity, https response error StatusCode: 0, RequestID: , request send failed, Post "https://sts/..amazonaws.com/": dial tcp: lookup sts..amazonaws.com: no such host
```
The note about `config set aws:region` only shows up in this error case,
so clearly actionable.


For comparison, upstream, no credentials configured:
```
│ Error: configuring Terraform AWS Provider: no valid credential sources for Terraform AWS Provider found.
│
│ Please see https://registry.terraform.io/providers/hashicorp/aws
│ for more information about providing credentials.
│
│ AWS Error: failed to refresh cached credentials, no EC2 IMDS role found, operation error ec2imds: GetMetadata, http response error StatusCode: 404, request to EC2 IMDS failed
│
│
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on main.tf line 12, in provider "aws":
│   12: provider "aws" {
│
╵
```